### ISSUE TITLE
free-keys-keys multicharacter key

### ISSUE THREAD

**Issue by jtamagnan** [Fuco1/free-keys#3]
What would you think about adding an option to use multi-letter keys such as "TAB" to the free-keys-keys list.

I could add this feature if you would be willing to accept it in a pull request. Instead of having it be a string such as "abcdef" changing it to be ("a" "b" "c" "d" "TAB"). It would also have to work if it were a string, for backwards compatibility.

**Comment by Fuco1** [comment]
Definitely a good idea.  I basically went with a string because having a list of 100 items seemed ugly in the customize interface :D

But if you customize through elisp it doesn't really matter.

**Comment by jtamagnan** [comment]
I meant to do this and completely forgot! Thank you! Cheers

**Comment by Fuco1** [comment]
No problem :) I'm doing a bit of a summer cleanup (I missed the spring one :D)
