### ISSUE TITLE
Please release free-keys on MELPA stable

### ISSUE THREAD

**Issue by sixpointzero** [Fuco1/free-keys#4]
free-keys hasn't seen a release on [MELPA stable](https://stable.melpa.org/) yet. Please consider releasing free-keys on MELPA stable.

**Comment by Fuco1** [comment]
Is it enough if I add a tag?

**Comment by phikal** [comment]
Bumping this issue, I'd also like to add free-keys to NonGNU ELPA. That would require updating the [Version attribute](https://github.com/Fuco1/free-keys/blob/master/free-keys.el#L7). The current value hasn't been changed since the initial commit.

**Comment by Fuco1** [comment]
feel free to submit a pull request, I'm not familiar with packaging for nongnu elpa
