### ISSUE TITLE
suggested readme change

### ISSUE THREAD

**Issue by stevenjowens** [Fuco1/free-keys#5]
Hi, free-keys is a very useful package, thank you for writing it.  

I would like to suggest a clarification to the readme.  You wrote:

'If called with prefix argument C-u, you can specify a prefix map to be used, such as C-c or C-c C-x (these are specified as a string).'

It might be easier for users to understand if you describe it this way:

'Do "C-u M-x free-keys" and free-keys will prompt you for a prefix to use.  Enter the prefix as a plain string.  For example, if you want the prefix C-x, don't hold down the control key and press x, simply type the characters "C-x" at the "Prefix:" prompt.'

It took me a few minutes to figure out how to do this.  I kept trying to enter "C-x" as the argument to "C-u", for example:

hold down control key
tap u key
release control key
tap c key
tap - key
etc.

This did not work, of course, it ends up typing "CCCC-" into the buffer.

**Comment by Fuco1** [comment]
I find your version no worse than mine, so if it helps I'm all for it! :)  You can edit the file here directly on github and it will create a pull request for you.  Would you be intereted in doing that? (you'llget a contribution, yay :D)
