### ISSUE TITLE
free keys w no modifier

### ISSUE THREAD

**Issue by mooseyboots** [Fuco1/free-keys#7]
modes more for viewing and navigating stuff don't so much need modifiers keys for their bindings.

(modes that work like info).

wd be good if they too cd benefit from this kinda overview, e.g. by specifying no prefix.

**Comment by Fuco1** [comment]
I think it already works like that.  Open a help buffer and runn `M-x free-keys`

![image](https://user-images.githubusercontent.com/2664959/183148956-e95c96a0-6ddb-4672-8b43-546d3b801632.png)

**Comment by mooseyboots** [comment]
hm, it seems you are totally right! not sure how my mode was holding out on those ones, but now it's doing exactly as you say.
